version: '3.8'

services:
  db:
    image: postgres:17.6
    container_name: postgres-db
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - project-name-dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: kotlin-api-project-template-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    restart: always

volumes:
  project-name-dbdata: