insert into cuisine(id,name) values (1,'American');
insert into cuisine(id,name) values (2,'Chinese');
insert into cuisine(id,name) values (3,'Thai');
insert into cuisine(id,name) values (4,'Italian');
insert into cuisine(id,name) values (5,'French');
insert into cuisine(id,name) values (6,'Japanese');
insert into cuisine(id,name) values (7,'Turkish');
insert into cuisine(id,name) values (8,'Korean');
insert into cuisine(id,name) values (9,'Vietnamese');
insert into cuisine(id,name) values (10,'Indian');
insert into cuisine(id,name) values (11,'Spanish');
insert into cuisine(id,name) values (12,'Greek');
insert into cuisine(id,name) values (13,'Mexican');
insert into cuisine(id,name) values (14,'Malaysian');
insert into cuisine(id,name) values (15,'African');
insert into cuisine(id,name) values (16,'German');
insert into cuisine(id,name) values (17,'Indonesian');
insert into cuisine(id,name) values (18,'Russian');
insert into cuisine(id,name) values (19,'Other');

insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousgenix',4,1,10,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Herbed Delicious',4,7,20,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousscape',3,7,50,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hideaway Delicious',2,5,40,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cuts Delicious',3,9,25,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Lord Delicious',1,7,35,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hilltop Delicious',3,3,45,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fine Delicious',4,5,45,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousish',1,3,50,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Havana Delicious',3,1,35,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciouspad',3,10,40,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousbea',5,6,50,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousquipo',2,2,10,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fed Delicious',2,9,35,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hotspot Delicious',4,10,25,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Gusto Delicious',5,3,50,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciouszen',2,6,30,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciouszilla',4,1,15,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousio',5,9,40,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Local Delicious',5,4,20,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crisp Delicious',5,2,45,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciousoryx',1,5,25,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bang Delicious',5,2,15,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Deliciouszoid',3,2,30,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hearty ChowClick',2,6,25,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Traditional Chow',5,2,15,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bash Chow',2,6,45,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Minty Chow',4,8,35,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chowaza',3,9,20,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Lucha Chow',3,4,25,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hut Chow',2,2,10,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wish Chow',3,1,40,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chowish',3,8,10,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bazaar Chow',4,4,40,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Story Chow',2,10,30,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hideout Chow',2,7,10,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Strip Chow',5,9,35,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Aroma Chow',5,10,10,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chowology',5,9,30,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chowify',4,4,45,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Piece Chow',4,9,10,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cave Chow',3,4,40,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wagon Chow',3,9,10,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Choworyx',2,3,40,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Whole Chow',2,7,15,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Central Chow',3,7,45,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Ambrosial Chow',4,5,50,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Place Chow',2,2,15,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Reservation Table',4,3,20,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chopped Table',1,5,40,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Herbed Table',1,1,15,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palate Table',1,1,15,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grove Table',5,2,10,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fodder Table',4,1,20,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tablebes',4,2,40,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chow Table',1,1,10,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bay Table',3,7,50,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tablebea',1,7,25,10);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fine Table',2,5,15,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cellar Table',4,8,25,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Boy Table',3,9,30,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableomatic',1,5,20,16);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableque',4,3,10,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableio',3,3,40,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableoont',5,10,20,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableadora',5,2,25,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tableooze',3,1,50,16);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Garnish Table',4,9,40,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Brew Table',2,10,15,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hotspot Table',3,7,40,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fresh Table',3,2,30,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Appetite Table',1,10,40,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cave Tasty',5,10,15,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Whole Tasty',1,1,30,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastyio',3,10,30,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Lane Tasty',5,5,35,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Nouveau Tasty',1,9,50,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Relish Tasty',3,8,50,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastyooze',3,6,20,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Binge Tasty',1,8,10,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fed Tasty',3,5,25,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Diced Tasty',5,4,40,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastylux',5,8,35,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastyaza',3,7,45,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grill Tasty',2,2,30,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastyopolis',1,6,20,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Stand Tasty',4,3,40,16);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Feast Tasty',2,8,20,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Baby Tasty',3,1,20,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fodder Tasty',4,4,30,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Takeout Tasty',5,5,20,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wrap Tasty',1,10,30,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tastylia',3,4,50,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Havana Tasty',4,10,15,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crumb Tasty',2,5,25,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dished Tasty',1,7,25,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chop Grill',5,8,10,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Festive Grill',2,4,35,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Me Grill',5,5,25,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Lounge Grill',3,10,40,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Coastal Grill',2,7,10,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Perfection Grill',3,3,50,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hungry Grill',3,4,50,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cater Grill',4,3,50,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Presto Grill',5,2,40,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crispy Grill',1,7,45,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grilltastic',3,3,30,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grillsio',3,4,15,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tasteful Grill',5,9,10,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummy Grill',1,8,50,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crisp Grill',2,6,50,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grillya',2,7,40,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cuts Grill',1,7,30,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grillarc',2,3,25,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wish Grill',1,8,30,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dished Grill',3,1,10,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Divine Grill',1,9,25,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wedge Grill',2,4,35,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Gusto Grill',3,10,10,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chef Grill',5,4,35,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grove Palace',2,4,20,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Tasteful Palace',2,3,20,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Perfection Palace',3,1,20,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceio',4,7,45,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceado',3,6,25,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Flavor Palace',2,2,20,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceadri',4,8,50,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hotspot Palace',1,3,35,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceopedia',5,10,25,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Gusto Palace',5,10,30,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Feed Palace',2,5,20,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Smash Palace',1,9,10,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Gnaw Palace',1,3,50,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dished Palace',5,7,25,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Spicy PalaceClick to check domain availability.',2,6,10,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Nouveau Palace',3,8,15,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Relish Palace',2,3,40,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceistic',2,10,45,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palacearo',1,4,50,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Place Palace',5,2,40,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Aroma Palace',2,5,40,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fury Palace',5,3,30,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palacex',2,6,15,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palaceocity',1,7,25,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Ambrosial Yummy',3,7,50,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Nibble Yummy',1,8,15,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Accent Yummy',5,3,40,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummylia',1,1,40,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hotspot Yummy',1,3,45,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Chef Yummy',4,9,10,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Acclaimed Yummy',5,8,50,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummyella',2,3,40,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Palace Yummy',4,2,50,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Sizzle Yummy',3,1,15,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Galore Yummy',2,9,40,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummyquipo',2,3,45,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Divine Yummy',1,10,25,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Aladdin Yummy',1,4,30,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummyscape',1,3,35,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Yummylance',1,9,10,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crisp Yummy',1,10,25,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cantina Yummy',5,6,20,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Cellar Yummy',2,8,50,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Festive Yummy',2,2,25,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Upscale Yummy',2,10,45,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Lucha Yummy',1,10,40,3);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Diced Yummy',5,3,20,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Factory Yummy',4,3,15,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dude Kitchen',4,10,35,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchengenics',4,3,20,8);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Galore Kitchen',5,10,45,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Story Kitchen',5,3,20,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenbia',2,1,30,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fuel Kitchen',4,7,40,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dished Kitchen',5,3,30,14);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenish',3,2,20,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bang Kitchen',1,1,40,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bit Kitchen',1,1,30,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenlia',2,7,50,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenster',2,1,10,1);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Devine Kitchen',3,9,30,16);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Connoisseur Kitchen',2,6,30,19);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Munchies Kitchen',5,5,45,9);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Fine Kitchen',2,10,20,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Crisp Kitchen',1,3,35,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hut Kitchen',3,5,10,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenvio',3,1,50,12);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenarc',2,5,10,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Kitchenry',4,6,40,11);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Safety Kitchen',2,4,20,6);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Smash Kitchen',1,2,50,7);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Brew Kitchen',2,4,40,18);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Connoisseur Bar',2,2,25,17);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Bariva',5,10,40,10);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Barscape',3,4,15,4);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Hot Bar',4,4,20,2);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Place Bar',3,5,50,13);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Grill Bar',1,9,40,5);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Dine Bar',5,10,35,15);
insert into restaurant(name,customer_rating,distance,price,cuisine_id) values ('Wave Bar',4,8,20,3);